[package]
name = "postgres_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
postgres = "0.19.3"
postgres-openssl = "0.5.0"
openssl = "0.10.23"
dotenv = "0.15.0"